name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run lint -- --output-file eslint-results.sarif

      - name: Upload SARIF results (recommended)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif

      - name: Check ESLint results and fail workflow if errors are found
        if: always()
        run: |
          npx sarif-utils --level error eslint-results.sarif
          if [[ $? -eq 1 ]]; then
            echo "::error::ESLint found errors. Please fix them before merging."
            exit 1 # Fail the workflow
          fi